// Country codes with flags, phone prefixes, and phone lengths
export const COUNTRIES = [
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', dial: '+93', length: 9 },
  { name: 'Albania', code: 'AL', flag: '🇦🇱', dial: '+355', length: 9 },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿', dial: '+213', length: 9 },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩', dial: '+376', length: 6 },
  { name: 'Angola', code: 'AO', flag: '🇦🇴', dial: '+244', length: 9 },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷', dial: '+54', length: 10 },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲', dial: '+374', length: 8 },
  { name: 'Australia', code: 'AU', flag: '🇦🇺', dial: '+61', length: 9 },
  { name: 'Austria', code: 'AT', flag: '🇦🇹', dial: '+43', length: 10 },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', dial: '+994', length: 9 },
  { name: 'Bahamas', code: 'BS', flag: '🇧🇸', dial: '+1-242', length: 10 },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭', dial: '+973', length: 8 },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', dial: '+880', length: 10 },
  { name: 'Barbados', code: 'BB', flag: '🇧🇧', dial: '+1-246', length: 10 },
  { name: 'Belarus', code: 'BY', flag: '🇧🇾', dial: '+375', length: 9 },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪', dial: '+32', length: 9 },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿', dial: '+501', length: 7 },
  { name: 'Benin', code: 'BJ', flag: '🇧🇯', dial: '+229', length: 8 },
  { name: 'Bhutan', code: 'BT', flag: '🇧🇹', dial: '+975', length: 8 },
  { name: 'Bolivia', code: 'BO', flag: '🇧🇴', dial: '+591', length: 8 },
  { name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦', dial: '+387', length: 9 },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼', dial: '+267', length: 7 },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷', dial: '+55', length: 10 },
  { name: 'Brunei', code: 'BN', flag: '🇧🇳', dial: '+673', length: 7 },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬', dial: '+359', length: 9 },
  { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫', dial: '+226', length: 8 },
  { name: 'Burundi', code: 'BI', flag: '🇧🇮', dial: '+257', length: 8 },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭', dial: '+855', length: 9 },
  { name: 'Cameroon', code: 'CM', flag: '🇨🇲', dial: '+237', length: 9 },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', dial: '+1', length: 10 },
  { name: 'Cape Verde', code: 'CV', flag: '🇨🇻', dial: '+238', length: 7 },
  { name: 'Central African Republic', code: 'CF', flag: '🇨🇫', dial: '+236', length: 8 },
  { name: 'Chad', code: 'TD', flag: '🇹🇩', dial: '+235', length: 8 },
  { name: 'Chile', code: 'CL', flag: '🇨🇱', dial: '+56', length: 9 },
  { name: 'China', code: 'CN', flag: '🇨🇳', dial: '+86', length: 11 },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴', dial: '+57', length: 10 },
  { name: 'Comoros', code: 'KM', flag: '🇰🇲', dial: '+269', length: 7 },
  { name: 'Congo', code: 'CG', flag: '🇨🇬', dial: '+242', length: 9 },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', dial: '+506', length: 8 },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷', dial: '+385', length: 9 },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺', dial: '+53', length: 8 },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾', dial: '+357', length: 8 },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿', dial: '+420', length: 9 },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰', dial: '+45', length: 8 },
  { name: 'Djibouti', code: 'DJ', flag: '🇩🇯', dial: '+253', length: 8 },
  { name: 'Dominica', code: 'DM', flag: '🇩🇲', dial: '+1-767', length: 10 },
  { name: 'Dominican Republic', code: 'DO', flag: '🇩🇴', dial: '+1-809', length: 10 },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨', dial: '+593', length: 9 },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', dial: '+20', length: 10 },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻', dial: '+503', length: 8 },
  { name: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶', dial: '+240', length: 9 },
  { name: 'Eritrea', code: 'ER', flag: '🇪🇷', dial: '+291', length: 7 },
  { name: 'Estonia', code: 'EE', flag: '🇪🇪', dial: '+372', length: 8 },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', dial: '+251', length: 9 },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯', dial: '+679', length: 7 },
  { name: 'Finland', code: 'FI', flag: '🇫🇮', dial: '+358', length: 9 },
  { name: 'France', code: 'FR', flag: '🇫🇷', dial: '+33', length: 9 },
  { name: 'Gabon', code: 'GA', flag: '🇬🇦', dial: '+241', length: 8 },
  { name: 'Gambia', code: 'GM', flag: '🇬🇲', dial: '+220', length: 7 },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪', dial: '+995', length: 9 },
  { name: 'Germany', code: 'DE', flag: '🇩🇪', dial: '+49', length: 11 },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', dial: '+233', length: 9 },
  { name: 'Greece', code: 'GR', flag: '🇬🇷', dial: '+30', length: 10 },
  { name: 'Grenada', code: 'GD', flag: '🇬🇩', dial: '+1-473', length: 10 },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹', dial: '+502', length: 8 },
  { name: 'Guinea', code: 'GN', flag: '🇬🇳', dial: '+224', length: 8 },
  { name: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼', dial: '+245', length: 7 },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾', dial: '+592', length: 7 },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹', dial: '+509', length: 8 },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳', dial: '+504', length: 8 },
  { name: 'Hong Kong', code: 'HK', flag: '🇭🇰', dial: '+852', length: 8 },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺', dial: '+36', length: 9 },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸', dial: '+354', length: 7 },
  { name: 'India', code: 'IN', flag: '🇮🇳', dial: '+91', length: 10 },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩', dial: '+62', length: 10 },
  { name: 'Iran', code: 'IR', flag: '🇮🇷', dial: '+98', length: 10 },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶', dial: '+964', length: 10 },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪', dial: '+353', length: 9 },
  { name: 'Israel', code: 'IL', flag: '🇮🇱', dial: '+972', length: 9 },
  { name: 'Italy', code: 'IT', flag: '🇮🇹', dial: '+39', length: 10 },
  { name: 'Ivory Coast', code: 'CI', flag: '🇨🇮', dial: '+225', length: 8 },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲', dial: '+1-876', length: 10 },
  { name: 'Japan', code: 'JP', flag: '🇯🇵', dial: '+81', length: 10 },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴', dial: '+962', length: 9 },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', dial: '+7', length: 10 },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', dial: '+254', length: 9 },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮', dial: '+686', length: 5 },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼', dial: '+965', length: 8 },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', dial: '+996', length: 9 },
  { name: 'Laos', code: 'LA', flag: '🇱🇦', dial: '+856', length: 9 },
  { name: 'Latvia', code: 'LV', flag: '🇱🇻', dial: '+371', length: 8 },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧', dial: '+961', length: 8 },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸', dial: '+266', length: 8 },
  { name: 'Liberia', code: 'LR', flag: '🇱🇷', dial: '+231', length: 8 },
  { name: 'Libya', code: 'LY', flag: '🇱🇾', dial: '+218', length: 9 },
  { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮', dial: '+423', length: 7 },
  { name: 'Lithuania', code: 'LT', flag: '🇱🇹', dial: '+370', length: 8 },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', dial: '+352', length: 9 },
  { name: 'Macao', code: 'MO', flag: '🇲🇴', dial: '+853', length: 8 },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬', dial: '+261', length: 9 },
  { name: 'Malawi', code: 'MW', flag: '🇲🇼', dial: '+265', length: 9 },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾', dial: '+60', length: 9 },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻', dial: '+960', length: 7 },
  { name: 'Mali', code: 'ML', flag: '🇲🇱', dial: '+223', length: 8 },
  { name: 'Malta', code: 'MT', flag: '🇲🇹', dial: '+356', length: 8 },
  { name: 'Marshall Islands', code: 'MH', flag: '🇲🇭', dial: '+692', length: 7 },
  { name: 'Mauritania', code: 'MR', flag: '🇲🇷', dial: '+222', length: 8 },
  { name: 'Mauritius', code: 'MU', flag: '🇲🇺', dial: '+230', length: 8 },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽', dial: '+52', length: 10 },
  { name: 'Micronesia', code: 'FM', flag: '🇫🇲', dial: '+691', length: 7 },
  { name: 'Moldova', code: 'MD', flag: '🇲🇩', dial: '+373', length: 8 },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨', dial: '+377', length: 8 },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳', dial: '+976', length: 8 },
  { name: 'Montenegro', code: 'ME', flag: '🇲🇪', dial: '+382', length: 8 },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', dial: '+212', length: 9 },
  { name: 'Mozambique', code: 'MZ', flag: '🇲🇿', dial: '+258', length: 9 },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲', dial: '+95', length: 9 },
  { name: 'Namibia', code: 'NA', flag: '🇳🇦', dial: '+264', length: 8 },
  { name: 'Nauru', code: 'NR', flag: '🇳🇷', dial: '+674', length: 4 },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵', dial: '+977', length: 10 },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱', dial: '+31', length: 9 },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', dial: '+64', length: 9 },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', dial: '+505', length: 8 },
  { name: 'Niger', code: 'NE', flag: '🇳🇪', dial: '+227', length: 8 },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', dial: '+234', length: 10 },
  { name: 'North Korea', code: 'KP', flag: '🇰🇵', dial: '+850', length: 9 },
  { name: 'North Macedonia', code: 'MK', flag: '🇲🇰', dial: '+389', length: 8 },
  { name: 'Norway', code: 'NO', flag: '🇳🇴', dial: '+47', length: 8 },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', dial: '+968', length: 8 },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', dial: '+92', length: 10 },
  { name: 'Palau', code: 'PW', flag: '🇵🇼', dial: '+680', length: 7 },
  { name: 'Palestine', code: 'PS', flag: '🇵🇸', dial: '+970', length: 9 },
  { name: 'Panama', code: 'PA', flag: '🇵🇦', dial: '+507', length: 8 },
  { name: 'Papua New Guinea', code: 'PG', flag: '🇵🇬', dial: '+675', length: 8 },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾', dial: '+595', length: 9 },
  { name: 'Peru', code: 'PE', flag: '🇵🇪', dial: '+51', length: 9 },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭', dial: '+63', length: 10 },
  { name: 'Poland', code: 'PL', flag: '🇵🇱', dial: '+48', length: 9 },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', dial: '+351', length: 9 },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', dial: '+974', length: 8 },
  { name: 'Romania', code: 'RO', flag: '🇷🇴', dial: '+40', length: 9 },
  { name: 'Russia', code: 'RU', flag: '🇷🇺', dial: '+7', length: 10 },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼', dial: '+250', length: 9 },
  { name: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳', dial: '+1-869', length: 10 },
  { name: 'Saint Lucia', code: 'LC', flag: '🇱🇨', dial: '+1-758', length: 10 },
  { name: 'Saint Vincent', code: 'VC', flag: '🇻🇨', dial: '+1-784', length: 10 },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸', dial: '+685', length: 7 },
  { name: 'San Marino', code: 'SM', flag: '🇸🇲', dial: '+378', length: 7 },
  { name: 'Sao Tome and Principe', code: 'ST', flag: '🇸🇹', dial: '+239', length: 7 },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', dial: '+966', length: 9 },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳', dial: '+221', length: 9 },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸', dial: '+381', length: 9 },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨', dial: '+248', length: 7 },
  { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱', dial: '+232', length: 8 },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬', dial: '+65', length: 8 },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰', dial: '+421', length: 9 },
  { name: 'Slovenia', code: 'SI', flag: '🇸🇮', dial: '+386', length: 9 },
  { name: 'Solomon Islands', code: 'SB', flag: '🇸🇧', dial: '+677', length: 5 },
  { name: 'Somalia', code: 'SO', flag: '🇸🇴', dial: '+252', length: 8 },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', dial: '+27', length: 9 },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷', dial: '+82', length: 10 },
  { name: 'South Sudan', code: 'SS', flag: '🇸🇸', dial: '+211', length: 9 },
  { name: 'Spain', code: 'ES', flag: '🇪🇸', dial: '+34', length: 9 },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', dial: '+94', length: 9 },
  { name: 'Sudan', code: 'SD', flag: '🇸🇩', dial: '+249', length: 9 },
  { name: 'Suriname', code: 'SR', flag: '🇸🇷', dial: '+597', length: 7 },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪', dial: '+46', length: 9 },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭', dial: '+41', length: 9 },
  { name: 'Syria', code: 'SY', flag: '🇸🇾', dial: '+963', length: 9 },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼', dial: '+886', length: 9 },
  { name: 'Tajikistan', code: 'TJ', flag: '🇹🇯', dial: '+992', length: 9 },
  { name: 'Tanzania', code: 'TZ', flag: '🇹🇿', dial: '+255', length: 9 },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭', dial: '+66', length: 9 },
  { name: 'Timor-Leste', code: 'TL', flag: '🇹🇱', dial: '+670', length: 8 },
  { name: 'Togo', code: 'TG', flag: '🇹🇬', dial: '+228', length: 8 },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴', dial: '+676', length: 5 },
  { name: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹', dial: '+1-868', length: 10 },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳', dial: '+216', length: 8 },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷', dial: '+90', length: 10 },
  { name: 'Turkmenistan', code: 'TM', flag: '🇹🇲', dial: '+993', length: 8 },
  { name: 'Tuvalu', code: 'TV', flag: '🇹🇻', dial: '+688', length: 5 },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬', dial: '+256', length: 9 },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦', dial: '+380', length: 9 },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', dial: '+971', length: 9 },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', dial: '+44', length: 10 },
  { name: 'United States', code: 'US', flag: '🇺🇸', dial: '+1', length: 10 },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾', dial: '+598', length: 8 },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', dial: '+998', length: 9 },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺', dial: '+678', length: 5 },
  { name: 'Vatican City', code: 'VA', flag: '🇻🇦', dial: '+379', length: 6 },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪', dial: '+58', length: 10 },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳', dial: '+84', length: 9 },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪', dial: '+967', length: 9 },
  { name: 'Zambia', code: 'ZM', flag: '🇿🇲', dial: '+260', length: 9 },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', dial: '+263', length: 9 },
];
