-- Migration: create applications and carts tables

BEGIN;

-- applications table
CREATE TABLE IF NOT EXISTS public.applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NULL,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  course_name text NULL,
  program_name text NULL,
  qualification text NULL,
  experience text NULL,
  message text NULL,
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- carts table: one row per user storing JSON cart
CREATE TABLE IF NOT EXISTS public.carts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE,
  cart jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMIT;
