/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimpleEventRouteImport } from './routes/simple-event'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FellowshipRouteImport } from './routes/fellowship'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ContactRedirectRouteImport } from './routes/contact-redirect'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutDmhcaRouteImport } from './routes/about-dmhca'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopMedicalCoursesIndexRouteImport } from './routes/top-medical-courses.index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as SimpleEventSlugRouteImport } from './routes/simple-event.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CourseCategorySlugRouteImport } from './routes/course-category.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleEventRoute = SimpleEventRouteImport.update({
  id: '/simple-event',
  path: '/simple-event',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipRoute = FellowshipRouteImport.update({
  id: '/fellowship',
  path: '/fellowship',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRedirectRoute = ContactRedirectRouteImport.update({
  id: '/contact-redirect',
  path: '/contact-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDmhcaRoute = AboutDmhcaRouteImport.update({
  id: '/about-dmhca',
  path: '/about-dmhca',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopMedicalCoursesIndexRoute = TopMedicalCoursesIndexRouteImport.update({
  id: '/top-medical-courses/',
  path: '/top-medical-courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleEventSlugRoute = SimpleEventSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SimpleEventRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCategorySlugRoute = CourseCategorySlugRouteImport.update({
  id: '/course-category/$slug',
  path: '/course-category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-dmhca': typeof AboutDmhcaRoute
  '/blog': typeof BlogRoute
  '/contact-redirect': typeof ContactRedirectRoute
  '/contact-us': typeof ContactUsRoute
  '/faculty': typeof FacultyRoute
  '/fellowship': typeof FellowshipRoute
  '/login': typeof LoginRoute
  '/simple-event': typeof SimpleEventRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/course-category/$slug': typeof CourseCategorySlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/simple-event/$slug': typeof SimpleEventSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/top-medical-courses/': typeof TopMedicalCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-dmhca': typeof AboutDmhcaRoute
  '/blog': typeof BlogRoute
  '/contact-redirect': typeof ContactRedirectRoute
  '/contact-us': typeof ContactUsRoute
  '/faculty': typeof FacultyRoute
  '/fellowship': typeof FellowshipRoute
  '/login': typeof LoginRoute
  '/simple-event': typeof SimpleEventRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/course-category/$slug': typeof CourseCategorySlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/simple-event/$slug': typeof SimpleEventSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/top-medical-courses': typeof TopMedicalCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-dmhca': typeof AboutDmhcaRoute
  '/blog': typeof BlogRoute
  '/contact-redirect': typeof ContactRedirectRoute
  '/contact-us': typeof ContactUsRoute
  '/faculty': typeof FacultyRoute
  '/fellowship': typeof FellowshipRoute
  '/login': typeof LoginRoute
  '/simple-event': typeof SimpleEventRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/course-category/$slug': typeof CourseCategorySlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/simple-event/$slug': typeof SimpleEventSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/top-medical-courses/': typeof TopMedicalCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-dmhca'
    | '/blog'
    | '/contact-redirect'
    | '/contact-us'
    | '/faculty'
    | '/fellowship'
    | '/login'
    | '/simple-event'
    | '/sitemap.xml'
    | '/course-category/$slug'
    | '/courses/$slug'
    | '/simple-event/$slug'
    | '/sitemap/xml'
    | '/top-medical-courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-dmhca'
    | '/blog'
    | '/contact-redirect'
    | '/contact-us'
    | '/faculty'
    | '/fellowship'
    | '/login'
    | '/simple-event'
    | '/sitemap.xml'
    | '/course-category/$slug'
    | '/courses/$slug'
    | '/simple-event/$slug'
    | '/sitemap/xml'
    | '/top-medical-courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-dmhca'
    | '/blog'
    | '/contact-redirect'
    | '/contact-us'
    | '/faculty'
    | '/fellowship'
    | '/login'
    | '/simple-event'
    | '/sitemap.xml'
    | '/course-category/$slug'
    | '/courses/$slug'
    | '/simple-event/$slug'
    | '/sitemap/xml'
    | '/top-medical-courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutDmhcaRoute: typeof AboutDmhcaRoute
  BlogRoute: typeof BlogRoute
  ContactRedirectRoute: typeof ContactRedirectRoute
  ContactUsRoute: typeof ContactUsRoute
  FacultyRoute: typeof FacultyRoute
  FellowshipRoute: typeof FellowshipRoute
  LoginRoute: typeof LoginRoute
  SimpleEventRoute: typeof SimpleEventRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CourseCategorySlugRoute: typeof CourseCategorySlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  TopMedicalCoursesIndexRoute: typeof TopMedicalCoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-event': {
      id: '/simple-event'
      path: '/simple-event'
      fullPath: '/simple-event'
      preLoaderRoute: typeof SimpleEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowship': {
      id: '/fellowship'
      path: '/fellowship'
      fullPath: '/fellowship'
      preLoaderRoute: typeof FellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-redirect': {
      id: '/contact-redirect'
      path: '/contact-redirect'
      fullPath: '/contact-redirect'
      preLoaderRoute: typeof ContactRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-dmhca': {
      id: '/about-dmhca'
      path: '/about-dmhca'
      fullPath: '/about-dmhca'
      preLoaderRoute: typeof AboutDmhcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-medical-courses/': {
      id: '/top-medical-courses/'
      path: '/top-medical-courses'
      fullPath: '/top-medical-courses/'
      preLoaderRoute: typeof TopMedicalCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-event/$slug': {
      id: '/simple-event/$slug'
      path: '/$slug'
      fullPath: '/simple-event/$slug'
      preLoaderRoute: typeof SimpleEventSlugRouteImport
      parentRoute: typeof SimpleEventRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-category/$slug': {
      id: '/course-category/$slug'
      path: '/course-category/$slug'
      fullPath: '/course-category/$slug'
      preLoaderRoute: typeof CourseCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SimpleEventRouteChildren {
  SimpleEventSlugRoute: typeof SimpleEventSlugRoute
}

const SimpleEventRouteChildren: SimpleEventRouteChildren = {
  SimpleEventSlugRoute: SimpleEventSlugRoute,
}

const SimpleEventRouteWithChildren = SimpleEventRoute._addFileChildren(
  SimpleEventRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutDmhcaRoute: AboutDmhcaRoute,
  BlogRoute: BlogRoute,
  ContactRedirectRoute: ContactRedirectRoute,
  ContactUsRoute: ContactUsRoute,
  FacultyRoute: FacultyRoute,
  FellowshipRoute: FellowshipRoute,
  LoginRoute: LoginRoute,
  SimpleEventRoute: SimpleEventRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CourseCategorySlugRoute: CourseCategorySlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  TopMedicalCoursesIndexRoute: TopMedicalCoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
