-- Migration: Force schema cache refresh by recreating applications table
-- This resolves Supabase PostgREST PGRST204 schema cache errors

BEGIN;

-- Drop old table and policies to clear cache
DROP TABLE IF EXISTS public.applications CASCADE;

-- Recreate applications table with proper schema
CREATE TABLE public.applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NULL DEFAULT NULL,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  course_name text NULL DEFAULT NULL,
  program_name text NULL DEFAULT NULL,
  qualification text NULL DEFAULT NULL,
  experience text NULL DEFAULT NULL,
  message text NULL DEFAULT NULL,
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Create indexes for better query performance
CREATE INDEX idx_applications_user_id ON public.applications(user_id);
CREATE INDEX idx_applications_email ON public.applications(email);
CREATE INDEX idx_applications_created_at ON public.applications(created_at DESC);

-- Enable RLS
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (unauthenticated users)
CREATE POLICY "public_insert_applications" ON public.applications
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "public_select_applications" ON public.applications
  FOR SELECT
  USING (true);

CREATE POLICY "public_update_applications" ON public.applications
  FOR UPDATE
  USING (true);

CREATE POLICY "public_delete_applications" ON public.applications
  FOR DELETE
  USING (true);

-- Grant permissions
GRANT INSERT, SELECT, UPDATE ON public.applications TO anon;
GRANT INSERT, SELECT, UPDATE ON public.applications TO authenticated;

COMMIT;
